import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";

interface LayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps) {
  return (
    <html>
      <body>
        <div>
          <header>Header Content</header>
          <main>{children}</main>
          <footer>Footer Content</footer>
        </div>
      </body>
    </html>
  );
}
