import type { Metadata } from "next";
import "./globals.css";
import { ReactNode } from "react";
import DefaultLayout from "../components/DefaultLayout";

interface LayoutProps {
  children: ReactNode;
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({ children }: LayoutProps) {
  return (
    <html>
      <body>
        <DefaultLayout>{children}</DefaultLayout>
      </body>
    </html>
  );
}
