name: Build and Deploy Angular App

on:
  push:
    branches: [master]

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Setup web version basedon package.json version
        working-directory: ./app
        run: ./node_modules/.bin/handlebars --data package.json src/app/version.hbs --stdout > src/app/version.ts

      - name: Build the Angular app
        working-directory: ./app
        run: ./node_modules/.bin/ng build --configuration production --output-path=dist --base-href /

      - name: Copy built application to ./public
        run: mkdir -p ./public/app && cp -r app/dist/* ./public/app
