name: Build and Deploy Angular App

on:
  push:
    branches: [master]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full git history is fetched for versioning

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.11.1

      - name: Install dependencies
        working-directory: ./app
        run: npm ci

      - name: Increment version
        working-directory: ./app
        run: |
          npm version patch -m "Bump to version %s [skip ci]"
          echo "VERSION=$(jq -r .version package.json)" >> $GITHUB_ENV        

      - name: Setup web version based on package.json version
        working-directory: ./app
        run: ./node_modules/.bin/mustache package.json src/app/version.hbs > src/app/version.ts

      - name: Build the Angular app
        working-directory: ./app
        run: ./node_modules/.bin/ng build --configuration production --output-path=dist --base-href /

      - name: Copy built application to ./public
        run: mkdir -p ./public/app && cp -r app/dist/* ./public/app

      - name: Commit and push version bump
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./app/package.json
          git commit -m "Bump version to ${{ env.VERSION }} [skip ci]"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}        

      - name: Commit and push changes
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add ./public
          git commit -m "Add built Angular app to public folder, version ${{ env.VERSION }}"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
